name: weread note sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # 每 2 小时执行一次
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_PAGE: ${{ secrets.NOTION_PAGE }}
      WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
      CC_URL: ${{ secrets.CC_URL }}
      CC_ID: ${{ secrets.CC_ID }}
      CC_PASSWORD: ${{ secrets.CC_PASSWORD }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
   
      REF: ${{ github.ref }}
      REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Debug env vars
        run: |
          echo "NOTION_PAGE: $NOTION_PAGE"
          echo "NOTION_TOKEN: $NOTION_TOKEN"
          echo "WEREAD_COOKIE: $WEREAD_COOKIE"
          echo "BOOK_DATABASE_NAME: $BOOK_DATABASE_NAME"
          echo "CC_ID: $CC_ID"
          echo "CC_PASSWORD: $CC_PASSWORD"
          
      
            
      - name: weread book sync
        run: |
             python weread2notionpro/book.py
      - name: weread sync
        run: |
           python weread2notionpro/weread.py
      
